# Blog info
blog_name: ljuns
slogan: åšè‡ªå·±å–œæ¬¢çš„äº‹ï¼Œå–œæ¬¢è‡ªå·±åšçš„äº‹
# url: http://www.forsigner.com
url: https://ljuns.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/ljuns.jpeg

# Set favicon
# favicon: /favicon.ico

# For seo
keywords: Android,ç§»åŠ¨å¼€å‘

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: Project
    url: /project/
    target_blank: true #åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: Github
    url: https://github.com/ljuns
    target_blank: true
  # - name: Twitter
  #   url: https://twitter.com/forsigner
  #   target_blank: true

# config page nav
page_nav:
  - name: åšå®¢
    url: /archives/
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /category/
    target_blank: false
  # - name: æ ‡ç­¾
  #   url: /tags/
  #   target_blank: false
  # - name: å‹é“¾
  #   url: /link/
  #   target_blank: false
  - name: å…³äº
    url: /about/
    target_blank: false
  # - name: Github
  #   url: https://github.com/ljuns
  #   target_blank: true
  # - name: RSS
  #   url: /atom.xml
  #   target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€
  # - name: æœç´¢
  #   url: /search/
  #   target_blank: false # åœ¨æ–°é¡µé¢æ‰“å¼€

page_nav_style:  ROUND_RECT  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: false # true|fase

# ç›’å­
toolbox:
  isShow: true # true|fase
  text: æ›´å¤š

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: äº¤æ¢å‹é“¾å¯ä»¥é‚®ä»¶ forsigner@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: æ‰«ä¸€æ‰«ï¼Œæ”¯æŒæˆ‘å§ï¼Œè°¢è°¢ğŸ™ğŸ™
  items:
    - type: å¾®ä¿¡
      text: å¾®ä¿¡æ‰«ä¸€æ‰«
      imgUrl: /images/weixin.png
    - type: æ”¯ä»˜å®
      text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
      imgUrl: /images/zhifubao.jpeg




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: /css/personal-style.css

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—èƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
home_background_scheme: light # darkã€light

# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST #HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
disqus_shortname: forsigner
# duoshuo_shortname: forsigner
gentie_key: dd5e8365d08c44c2a5949cdee496b67b

# ä¸ç®—å­,æ–‡ç« è®¿é—®é‡ç»Ÿè®¡å’Œæ˜¾ç¤º
busuanzi: true

# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "æœ‰ç‚¹å¸…çš„ Android å¼€å‘è€…"
    - "çˆ±ç”Ÿæ´»ï¼Œçˆ±åˆ†äº«ï¼Œçˆ± LOL"
    - "æ ¼è¨€ï¼šåšè‡ªå·±å–œæ¬¢çš„äº‹ï¼Œå–œæ¬¢è‡ªå·±åšçš„äº‹"
    - "è¿™é‡Œæ˜¯æˆ‘çš„åˆ†äº«ï¼Œä¹Ÿæ˜¯æˆ‘æˆé•¿çš„å†ç¨‹"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@ljuns"
    text_value_url: https://github.com/ljuns
  # - type: weibo
  #   icon: icon-weibo
  #   text_key: å¾®åš
  #   text_value: "@forsigner"
  #   text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "ljunsw@gmail.com"
  - type: location
    icon: icon-location
    text_value: å¹¿å·

link:
  - name: ç»‡ç½‘
    info: èº«ä½“å’Œçµé­‚ï¼Œæ€»æœ‰ä¸€ä¸ªåœ¨è·¯ä¸Š
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
  - name: Dongyado
    info: ç”Ÿå‘½ä¸æ­¢ï¼ŒæŠ˜è…¾ä¸æ¯
    url: http://dongyado.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: OrangeCoder
    info: android ffmpeg nodejs gradle
    url: http://orangecoder.com/
    avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
  - name: EverET
    info: å¥½è®°æ€§ä¸å¦‚çƒ‚ç¬”å¤´
    url: http://everet.org/about-me/
    avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
  - name: é¢˜å¶
    info: FP, GUI, Writing
    url: http://tiye.me/
    avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
  - name: McChen
    info: Stay Hungry, Stay Foolish
    url: http://mcchen.club/
    avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
  - type: personal
    name: web-fontmin
    url: https://github.com/forsigner/web-fontmin
    intro: å­—ä½“å­é›†åŒ–ï¼Œåœ¨çº¿æå–ä½ éœ€è¦çš„å­—ä½“
  - type: personal
    name: magic-check
    url: https://github.com/forsigner/magic-check
    intro: Beautify Radio and Checkbox with pure CSS
  - type: personal
    name: nice-bar
    url: https://github.com/forsigner/nice-bar
    intro: A nice and lightweight scrollbar
  - type: personal
    name: angular-nice-bar
    url: https://github.com/forsigner/angular-nice-bar
    intro: A nice and lightweight scrollbar in Angular
  - type: personal
    name: fo-popover
    url: https://github.com/forsigner/fo-popover
    intro: A nice popover for Angular
  - type: personal
    name: fo-tooltip
    url: A nice tooltip for Angular
    intro: https://github.com/forsigner/fo-tooltip
  - type: personal
    name: fo-modal
    url: https://github.com/forsigner/fo-modal
    intro: A nice modal for Angular
  - type: personal
    name: mocer
    url: https://github.com/forsigner/mocer
    intro: Setup a mock server easily
  - type: personal
    name: node-pngdefry
    url: https://github.com/forsigner/node-pngdefry
    intro: Repairing iPhone fried PNGs using Node.js
  - type: personal
    name: ng-simditor
    url: https://github.com/forsigner/ng-simditor
    intro: Angular directive for simditor
